title: Ufuk Hacıoğulları
description: Programming blog

url: https://ufukhaciogullari.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   github: uhaciogullari
   stackoverflow: https://stackoverflow.com/users/205859/ufuk-hac%C4%B1o%C4%9Fullar%C4%B1?tab=profile

google_analytics: "UA-36762110-3"
